[cerebrium.deployment]
name = "coding-compiler-server"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'codingcompilerserver.py', 'cerebrium.toml', 'requirements.txt']
exclude = ['.*']

[cerebrium.hardware]
cpu = 2
memory = 8.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 1
max_replicas = 3
cooldown = 30
replica_concurrency = 1
response_grace_period = 300
scaling_metric = "cpu_utilization"
scaling_target = 70

[cerebrium.dependencies]
paths = { pip = "requirements.txt" }

[cerebrium.runtime]
handler = "codingcompilerserver.handler"
timeout = 30